### ISSUE TITLE
flags.contains(0) == true

### ISSUE THREAD

**Issue by jdm** [rust-lang-nursery/bitflags#103]
The `contains` API is implemented as follows:
```
pub fn contains(&self, other: $BitFlags) -> bool {
    (*self & other) == other
}
```
This means that doing `flags.contains(SomeFlag::empty())` is true, which is counterintuitive.

**Comment by mbrubeck** [comment]
I don't consider this a bug, personally.  Bitflags values are sets, and in set theory, “A contains B” is always true for any set A if B is the empty set.

**Comment by dtolnay** [comment]
I agree, the 0 bitflag is the empty set which is contained in any set.
