### ISSUE TITLE
Publishing a new version

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang-nursery/bitflags#104]
0.8.2 contains `#[allow(private_in_public)]` for a flavor of private-in-public error that is *really* going to become an error (public reexport of a private extern crate).
I turned it into an error in rustc and during bootstrapping I discovered that bitflags 0.8.2 used by rustc are still using it.

**Comment by alexcrichton** [comment]
Done! I've published 0.9.0 with all the libs review changes
