### ISSUE TITLE
Documentation for specific flags aren't scoped

### ISSUE THREAD

**Issue by Susurrus** [rust-lang-nursery/bitflags#111]
In `nix` we use the `bitflags!` macro for grouping the various `libc` constants into datatypes for our functions. This provides some nice type safety, but unfortunately the generated documentation is not ideal. There are two problems with how `bitflags!` results in generated documentation:

1. The constants are all listed, ungrouped, in the module documentation ([see here](https://docs.rs/nix/0.9.0/nix/mqueue/index.html)).
2. The generated datatypes don't list their specific constants within their documentation. ([see here](https://docs.rs/nix/0.9.0/nix/mqueue/struct.MQ_OFlag.html)).

I'm not certain if this is fixable by `bitflags` without changes to `rustdoc`, but I'd prefer if the documentation for the generated datatypes more closely matched `Enum` types, which doesn't have either of the above problems.

Also relevant: nix-rust/nix#593

**Comment by dtolnay** [comment]
I think this will be resolved by moving to associated constants: #21. We will need to support documentation attributes on individual constants as well as on the bitflags struct as a whole.

```rust
pub struct Flags {
    bits: u32,
}

impl Flags {
    pub const A: Self = Flags { bits: 1 };
    pub const B: Self = Flags { bits: 2 };
    pub const C: Self = Flags { bits: 4 };
}
```

**Comment by robinst** [comment]
Seems to work since 1.0 was released, I think this issue can be closed now.

**Comment by Susurrus** [comment]
Indeed.
