### ISSUE TITLE
bitmask does not match with contains()

### ISSUE THREAD

**Issue by aep** [rust-lang-nursery/bitflags#116]
the behavior of contains doesn't match &

```
#[macro_use] extern crate bitflags;

bitflags! {
    pub struct Flags: u8 {
        const FlagA = 0xff;
    }
}

fn main() {
    println!("{}", Flags::from_bits(1).unwrap().contains(FlagA));
}

```
```
false
```

**Comment by dtolnay** [comment]
The doc says:

> contains: true all of the flags in other are contained within self

In this case all of the flags in FlagA (bits 0 through 7) are not contained in self (bit 0 only).

**Comment by aep** [comment]
makes sense, can we have a & operator then instead?

**Comment by dtolnay** [comment]
Yes, there is a `&` operator on Flags.

**Comment by aep** [comment]
yep. i missread an error message. sorry for the noise
