### ISSUE TITLE
Version 1.0.0 breaks compilation due to experimental feature

### ISSUE THREAD

**Issue by hadmut** [rust-lang-nursery/bitflags#128]
Hi, 

I'm currently learning rust on ubuntu, using the rust version 1.17.0 (which comes with ubuntu). I had a project compiling correctly just some days ago, using the image crate, but today it doesn't compile anymore, reason is the 1.0.0 release of bitflags:

   Compiling bitflags v1.0.0
error: associated constants are experimental (see issue #29646)
   --> /home/danisch/.cargo/registry/src/github.com-1ecc6299db9ec823/bitflags-1.0.0/src/lib.rs:441:17
    |
441 |                 pub const $Flag: $BitFlags = $BitFlags { bits: $value };
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | 
   ::: /home/danisch/.cargo/registry/src/github.com-1ecc6299db9ec823/bitflags-1.0.0/src/example_generated.rs
    |
4   | bitflags! {
    | - in this macro invocation

Since the image crate changed it's dependency on png (0.10.0 -> 0.11.0) without changing it's own version, and png 0.11.0 now depends on bitflags 1.0.0, I do no see how I can tell cargo to still use the older version of image (with the same version number) and it's older dependencies. 

Things don't compile now and I don't see how to get around.

**Comment by KodrAus** [comment]
Hi @hadmut!

That's a bit unfortunate that you've ended up with a project that refuses to build without you doing anything to it. 

The current stable version of Rust is `1.21.0`, which is a bit ahead of the package manager's `1.17.0`. I find the easiest way to manage a Rust installation is using the official [`rustup` tool](https://www.rust-lang.org/en-US/install.html). It's basically zero fuss, and lets you always target the latest stable version. There are a lot of libraries that track the latest stable version so I think you'll have the smoothest experience using `rustup`.

For this problem specifically it looks like they did bump `png` in a minor version bump, so if you include it in your `Cargo.toml` like this then you should get a pre `1.0` version of `bitflags`:

```
image = "0.16"
```

**Comment by hadmut** [comment]
Yeah, I just found out myself that the last working version of image was 0.16. Since I used different computers to work on it looked as if 0.17 had been working and had changed without increment of the release number. 

However, it's somewhat annoying that ruby, python, rust all come with their own upgrading procedures, causing a severe mess on computers. I therefore really hate those tools like rustup trying to fiddle around with my machine.

However, I've reported a bug to ubuntu asking them to keep the rust packages closer to the release upstream version. 

Maybe there should be some hint or directive which says "use at least rust x.xx to compile"

After all it turns out not to be a problem of bitflags, but of ubuntu and the rather unstable nature of rust. This shows that rust ist still not production ready.

thanks and regards
Hadmut

**Comment by dtolnay** [comment]
I wouldn't necessarily reach the same conclusion from this -- the version of gcc packaged by Ubuntu does not compile some C++17 libraries, but it would be wrong to conclude that C++ is not production ready.

I think the takeaway is that as long as your Cargo.toml is not using wildcard dependencies like `image = "*"`, you will not pick up breaking changes to libraries. With a version requirement for all of your dependencies like `image = "0.16"` in Cargo.toml, any code that compiles on a stable compiler today will compile tomorrow and on all future versions of Rust.

It sounds like you went from compiling with image 0.17 on a modern compiler to compiling with image 0.17 on a much older compiler, which is not guaranteed to work in general (in any language).

**Comment by hadmut** [comment]
I had reported a bug to ubuntu (compiler outdated), but based on the reply I received I cannot expect any upgraded packages from them. The ubuntu release 17.10 coming end of october will still have rust 1.18. 

i therefore started to learn to pack Ubuntu snaps (new kind of package format) to turn the rust compiler into a snap and have it clean and easily installed on several distributions, as listed on 
https://snapcraft.io/. 

That should easily solve the problem and keep the compiler to the lastest version while providing a clean package installation and removal, beeing more or less independent of distributions and their package policy.

**Comment by hadmut** [comment]
BTW, C++17 is a ISO/IEC standard an not just a new minor version of the compiler. And they don't release new C++ standards every few months.

**Comment by dtolnay** [comment]
Nice! Definitely make a post on the [Rust users forum](https://users.rust-lang.org/) when the snaps stuff is ready. I'm sure other people would find that useful.

**Comment by dtolnay** [comment]
Great, here is the forum thread about using a snap package to install recent Rust compilers without needing rustup.

<p align="center"><b><a href="https://users.rust-lang.org/t/rust-as-a-snap-package-for-several-linux-distributions/13463">https://users.rust-lang.org/t/rust-as-a-snap-package-for-several-linux-distributions/13463</a></b></p>

I am closing the issue because I don't think there is any followup needed in bitflags.
