### ISSUE TITLE
Representation Guarantees

### ISSUE THREAD

**Issue by cramertj** [rust-lang-nursery/bitflags#129]
Lots of people use this crate in order to autogenerate flags which interoperate with C code. However, this crate generates types of the form `struct Foo { bits: ReprType }`. Even with `repr(C)`, is this valid for FFI usage as `ReprType` without [`repr(transparent)`](https://github.com/rust-lang/rfcs/blob/master/text/1758-repr-transparent.md)? Every case I've seen in practice generated structures of the same size as `ReprType`, but is that actually guaranteed?

**Comment by alexcrichton** [comment]
These types are "valid" for FFI but not for a C function that's expecting a `u32`, for example. On Intel platforms I believe `u32` and `struct Foo(u32)` are passed the same way, but I believe on ARM those two types are passed differently in the ABI. Once we have `#[repr(transparent)]` though we should be able to guarantee it!

**Comment by cramertj** [comment]
Okay-- that's what I figured. Thanks!
