### ISSUE TITLE
Support building without core

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/bitflags#130]
As described in https://github.com/rust-lang/rust/pull/45079#issuecomment-336722610 bitflags currently depends on core [here](https://github.com/rust-lang-nursery/bitflags/blob/862582d107bb74ce4c7b505b2490eb815bc3a8c2/src/lib.rs#L231), but as a macro-only crate it shouldn't need to. This makes it impossible to use bitflags within the implementation of libcore.

**Comment by dtolnay** [comment]
@tamird may be interested in working on this.

**Comment by tamird** [comment]
Yep, was planning to work on that after https://github.com/rust-lang-nursery/bitflags/pull/127 merged. Could you give that a review?

**Comment by tamird** [comment]
OK, I pulled on this thread a bit, but it seems that `path` variables can't be chained. In other words, we'd need a separate path variable for every one of the identifiers being brought in, not just one for `core`. Am I missing something?

**Comment by dtolnay** [comment]
Is this what you mean by can't be chained?

```rust
macro_rules! m {
    ($p:path) => {
        use $p::HashMap;
        //    ^^ expected one of `;` or `as` here
    };
}

m!(std::collections);
```

If so, something like this might work as a workaround.

```rust
macro_rules! m {
    ($($p:ident)::+) => {
        use $($p)::+::HashMap;
    };
}
```

**Comment by tamird** [comment]
That's exactly what I meant, thank you! I'll try that.

**Comment by dtolnay** [comment]
We are not planning to pursue this. https://github.com/rust-lang-nursery/bitflags/pull/134#issuecomment-338702315
