### ISSUE TITLE
bitflags 1.0.1 fails to build on ubuntu xenial

### ISSUE THREAD

**Issue by jeking3** [rust-lang-nursery/bitflags#140]
{noformat}
error: expected ident, found #
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/bitflags-1.0.1/src/lib.rs:423:29
    |
423 |                             #[allow(deprecated)]
    |                             ^
    | 
   ::: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/bitflags-1.0.1/src/example_generated.rs
    |
4   | bitflags! {
    | - in this macro invocation
{noformat}

rustc 1.17 (Ubuntu Xenial)

Any idea what happened?

**Comment by jeking3** [comment]
Minimum supported version is Rust 1.20, due to usage of associated constants

**Comment by maretekent** [comment]
most crates may fail due to having a lower version that required. 
From time to time just do 
`rustup update`
