### ISSUE TITLE
Error while compiling bitflags as a dependency

### ISSUE THREAD

**Issue by evgeniysharapov** [rust-lang-nursery/bitflags#142]
I am trying to build and compile simple code that depends on `clap` which in turn has `bitflags` as a dependency. I am getting the error 

```
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling ansi_term v0.10.2
   Compiling bitflags v1.0.1
   Compiling winapi v0.2.8
   Compiling unicode-width v0.1.4
   Compiling strsim v0.6.0
   Compiling vec_map v0.8.0
   Compiling winapi-build v0.1.1
error: expected identifier, found keyword `in`
    --> C:\Users\evgeniy.sharapov\.cargo\registry\src\github.com-1ecc6299db9ec823\bitflags-1.0.1\src\lib.rs:1148:22
     |
1148 |                 pub (in super) fn value() -> u8 {
     |                      ^^

error: aborting due to previous error

error: Could not compile `bitflags`.
Build failed, waiting for other jobs to finish...
```
Am I missing something ? How could it have an error in the code ? 
I am using  rustc 1.16.0 (30cf806ef 2017-03-10) and cargo-0.17.0-nightly (f9e5481 2017-03-03)

**Comment by dtolnay** [comment]
I believe bitflags 1.0 requires a Rust compiler 1.20.0 or newer. [Rust Version Support](https://github.com/rust-lang-nursery/bitflags#rust-version-support)

**Comment by evgeniysharapov** [comment]
ok. It's true. I updated rust and it all works now. thank  you
