### ISSUE TITLE
Any example in the documentation?

### ISSUE THREAD

**Issue by Narann** [rust-lang-nursery/bitflags#19]
Hello!

Any hope to have a tiny example on how to use the macro in the documentation? :)

Thanks in advance! :)

**Comment by lberezy** [comment]
I'd like to second this.

**Comment by CraZySacX** [comment]
I think this can be closed.  [Example in the doc](https://doc.rust-lang.org/bitflags/bitflags/macro.bitflags!.html) near the bottom.

**Comment by Narann** [comment]
Cool! Thanks! :)
