### ISSUE TITLE
Allow namespaced flags

### ISSUE THREAD

**Issue by mathstuf** [rust-lang-nursery/bitflags#20]
It would be nice to have `FlagType::FlagName` be the pattern rather than dumping the flag values into the top-level namespace. Is this possible?

**Comment by rhoot** [comment]
Seems like this is not possible until the [associated_consts feature](https://github.com/rust-lang/rust/issues/17307) is done and allowed in stable rust. Looking forward to that!

**Comment by gsingh93** [comment]
Will namespaced constants using associated consts allow us to pattern match exhaustively on the flag names?

**Comment by felixc** [comment]
In the interim, wrapping the whole definition in a `mod` at least gets you a namespace. E.g.:

```rust
pub mod xmp_packet_fmt {
    bitflags! {
        pub flags GExiv2XmpFormatFlags: u64 {
            const OMIT_PACKET_WRAPPER   = 0x0010,
            const READ_ONLY_PACKET      = 0x0020,
            const USE_COMPACT_FORMAT    = 0x0040,
            const INCLUDE_THUMBNAIL_PAD = 0x0100,
            const EXACT_PACKET_LENGTH   = 0x0200,
            const WRITE_ALIAS_COMMENTS  = 0x0400,
            const OMIT_ALL_FORMATTING   = 0x0800,
        }
    }
}

println!("{:?}", xmp_packet_fmt::INCLUDE_THUMBNAIL_PAD);
```

**Comment by dtolnay** [comment]
> Will namespaced constants using associated consts allow us to pattern match exhaustively on the flag names?

No I don't think so.

**Comment by dtolnay** [comment]
It seems pretty clear at this point that associated constants are the answer to this, so let's track namespacing as part of #21.
