### ISSUE TITLE
Bitflags should be private by default

### ISSUE THREAD

**Issue by Amanieu** [rust-lang-nursery/bitflags#25]
Bitflags should match the semantics of structs, which are private by default unless explicitly exported using `pub`.

Since this is a compat-breaking change, it would make sense to do it at the same time as the switch to associated constants and namespaced flags (#24).

Example:
```rust
bitflags! {
    pub flags Flags: u32 {
        const FLAG_A   = 0b00000001,
        const FLAG_B   = 0b00000010,
    }
}
```

**Comment by xitep** [comment]
hello, it looks like after this change bitflags are _forced_ to standard types, e.g. u32. is this an accident or purpose?

the `lmdb-rs` project - which i tried upgrading to the latest stable of bitflags - uses amongst others [libc::c_uint in its bitflags definitions.](https://github.com/vhbit/lmdb-rs/blob/master/src/core.rs#L183) but i see no possibility to include the corresponding `use libc::c_uint` declaration in the newly generated `dummy` module.

any advice for me?
