### ISSUE TITLE
Allow using imported types

### ISSUE THREAD

**Issue by xitep** [rust-lang-nursery/bitflags#39]
In short, the following should be possible:

```
extern crate libc;
use libc::c_uint;
mod constants;

bitflags! {
    pub flags EnvFlags: c_uint {
        const EnvNoSync = constants::MDB_NOSYNC,
       // ...
    }
}
```

As of #38, the above example will not compile. As a workaround, one can reference the imported types/modules within the bitflags definition using absolute paths, e.g. using `::libc::c_uint` instead of `c_uint` or `::constants::MDB_NOSYNC` instead of `constants::MDB_NOSYNC`. This is, at least, surprising.

**Comment by dimbleby** [comment]
I've been unable even to find a workaround that will allow an example like this to compile with 0.5.0:

```rust
extern crate foo_sys;

bitflags! {
   flags FooFlags: i32 {
        const Flag1 = foo_sys::flag1,
        // ...
    }
}
```

... as for example [here](https://github.com/dimbleby/rust-c-ares/blob/76f1bdd44dcf0ee5497f5a68ecd41bf29701b4ef/src/ni_flags.rs).

Probably I'm missing some incantation.  But was it intended that such things should break?

**Comment by alexcrichton** [comment]
Right now the workaround is to use absolute paths, but it's unfortunately not great yeah

**Comment by dimbleby** [comment]
But I don't think that this workaround works in this case, does it?  Or if you think that it does, could you spell out for me how I can apply it?

Thanks!

**Comment by alexcrichton** [comment]
Ah it may not work, I haven't personally tested it myself

**Comment by xitep** [comment]
@dimbleby ... the following works for me:

```
#[macro_use]
extern crate bitflags;
extern crate liblmdb_sys;

bitflags!(
    pub flags Foo: i32 {
        const ONE = ::liblmdb_sys::MDB_NOTFOUND,
        const TWO = ::liblmdb_sys::MDB_KEYEXIST,
    }
);

fn main() {
    println!("{:?}", ONE | TWO);
}
```

**Comment by dimbleby** [comment]
Hmm.  When I make the same change in my code (linked above) I get errors like this:

```
src/ni_flags.rs:7:24: 7:34 error: failed to resolve. Did you mean `self::c_ares_sys`? [E0433]
src/ni_flags.rs:7         const NOFQDN = ::c_ares_sys::ARES_NI_NOFQDN,
                                         ^~~~~~~~~~
<bitflags macros>:139:1: 141:63 note: in this expansion of bitflags! (defined in <bitflags macros>)
src/ni_flags.rs:3:1: 39:3 note: in this expansion of bitflags! (defined in <bitflags macros>)
src/ni_flags.rs:7:24: 7:34 help: run `rustc --explain E0433` to see a detailed explanation
src/ni_flags.rs:7:24: 7:52 error: unresolved name `c_ares_sys::ARES_NI_NOFQDN` [E0425]
src/ni_flags.rs:7         const NOFQDN = ::c_ares_sys::ARES_NI_NOFQDN,
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

What's the difference?

**Comment by mzabaluev** [comment]
I'd rather have this unbroken than enjoy the cosmetic benefits of #14.
But perhaps the implementation in the inner modules could use `u64` instead of the parameter type?

**Comment by mzabaluev** [comment]
Note also this reimplementation by @Amanieu: https://github.com/rust-lang-nursery/bitflags/issues/21#issuecomment-160230866

**Comment by nox** [comment]
Any way we could fix this @alexcrichton?

**Comment by alexcrichton** [comment]
PRs always welcome! I suspect the fix would be pretty simple

**Comment by Amanieu** [comment]
I tried fixing this myself a while back but I couldn't get it to work properly with macro hygiene.

**Comment by nox** [comment]
@alexcrichton I tried too, hence me asking you to look into it. :)

**Comment by alexcrichton** [comment]
We can probably just revert the PR that introduced this, IIRC it's a feature that wasn't as nice to have as what this bug is about.

**Comment by brson** [comment]
Fixed.
