### ISSUE TITLE
Resolve clippy lints

### ISSUE THREAD

**Issue by kbknapp** [rust-lang-nursery/bitflags#41]
When using this lib as a dep, and running [clippy](https://github.com/Manishearth/rust-clippy) across the project, this dependency fails a few trivial lints, this prevents things like causing clippy to fail a CI build. The lints in question are:
- `if_not_else` (Needless `!` which can be removed by swapping `if` and `else` branches)
- [`used_underscore_binding`](https://github.com/Manishearth/rust-clippy/wiki#used_underscore_binding)

I haven't looked at the source for this project at all, but if it's just a trivial change, and doesn't affect the underlying methodology I'd be happy to submit a PR fixing these.

Thanks for this lib too!

**Comment by Manishearth** [comment]
Clippy ignores this lint for double-underscored values, which are usually found in macros. Rustc follows this convention, perhaps bitflags whould too?

**Comment by brson** [comment]
Let's use double-underscores for that lint.

**Comment by brson** [comment]
Next step is to run clippy again and see what it complains about, fix what can be. Use double underscores to solve some problems.

**Comment by robo9k** [comment]
When running `clippy` I only see one warning which is none of the ones @kbknapp reported:
```sh
$ cargo clippy --version
0.0.122
$ cargo clippy
warning: useless lint attribute
   --> src/lib.rs:176:1
    |
176 | #[allow(private_in_public)]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: #[warn(useless_attribute)] on by default
help: if you just forgot a `!`, use
    | #![allow(private_in_public)]
    = help: for further information visit https://github.com/Manishearth/rust-clippy/wiki#useless_attribute
```

Am I missing something here? I see #40 but nothing about the underscores (#33 maybe?).

**Comment by opilar** [comment]
When I remove `#[allow(private_in_public)]` clippy tells that:

```rust
warning: extern crate `core` is private, and cannot be reexported (error E0364), consider declaring with `pub`
   --> src/lib.rs:177:9
    |
177 | pub use core as __core;
    |         ^^^^^^^^^^^^^^
    |
    = note: #[warn(private_in_public)] on by default
    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
    = note: for more information, see issue #34537 <https://github.com/rust-lang/rust/issues/34537>
```

`pub use core as __core;` is just the workaround for no std crates. 

It's either a clippy bug or the dirty bitflags hack.

**Comment by brson** [comment]
@robo9k @opilar I am not sure what's going on here or what the solution is.

Since the compiler sees this as being a bogus pattern that will become a hard error, this seems like a problem in need of a fix pretty desperately.

cc @rust-lang-nursery/libs

**Comment by brson** [comment]
win-api does slightly differently: https://github.com/retep998/winapi-rs/blob/dev/src/lib.rs#L18

```
#[doc(hidden)]
pub extern crate core as _core;
```

Let's try that way instead?

Thanks @retep998

**Comment by opilar** [comment]
@brson good to go!
