### ISSUE TITLE
Using bitflags with libc types broke in 0.5.

### ISSUE THREAD

**Issue by ahmedcharles** [rust-lang-nursery/bitflags#43]
https://github.com/rust-lang-nursery/bitflags/commit/351a632bb0b9be82be55e585132ac1ecbca3ddf7 seems to have broken code which uses libc::c_int as the type of the flags. I'm not sure if libc::c_int is supported or not, since it is an integer type, though it is in some sense, user defined...

```rust
#[macro_use]
extern crate bitflags;

extern crate libc;

use libc::c_int;

bitflags! {
    /// baz
    flags Flags: c_int {
        const A       = 0b00000001,
        #[doc = "bar"]
        const B       = 0b00000010,
        const C       = 0b00000100,
        #[doc = "foo"]
        const ABC     = A.bits | B.bits | C.bits,
    }
}

#[test]
fn smoke() {
    assert_eq!(ABC, A | B | C);
}
```

This worked before this commit, but fails after.

**Comment by dimbleby** [comment]
Duplicate #39, isn't it?

**Comment by ahmedcharles** [comment]
Yes, it is.
