### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by alexreg** [rust-lang-nursery/bitflags#53]
Are structs created using the `bitflags` macro recommended to be used in raw FFI bindings, i.e. within function signatures (this involves giving the attribute `repr(C)` to the struct, but seems to work) – or only using them in higher-level bindings?

**Comment by alexcrichton** [comment]
The ABI for structs passed by value is unfortunately subtly different for immediates of the same size on some architectures. That is, the ABI differs for the bitflags struct vs the underlying bits. As a result I'd recommend using the bits in FFI bindings, not the structs generated by this library

**Comment by alexreg** [comment]
I'm not sure what an "immediate" is, but I think I get what you mean... (Also, we're talking about C ABIs here, right?) Looks like I'll have to sacrifice a bit of type safety in the raw bindings, unfortunately.

**Comment by Yamakaky** [comment]
Do you have an example where it doesn't work, or a piece of doc that says it? It should be added in the doc since using the generated struct as the raw flags seems natural for ffi.
