### ISSUE TITLE
Document the minimum supported Rust version

### ISSUE THREAD

**Issue by fiveop** [rust-lang-nursery/bitflags#54]
With #47 bitflags no longer builds on various older versions (at least 1.7 and older). Is this intentional?

**Comment by nox** [comment]
> With rust 1.8, augmented_assignments and op_assign_traits are stable. Thus
just enable them globally.

It was definitely intentional.

**Comment by Susurrus** [comment]
I think it'd still be useful to have the minimum supported Rust version explicitly documented in the README.

**Comment by dtolnay** [comment]
As part of this, let's make sure to test that version in Travis. That way we avoid unintentionally breaking the minimum version. Currently Travis only runs stable/beta/nightly.

**Comment by tamird** [comment]
with #24 merged, the minimum version is now 1.20
