### ISSUE TITLE
breaking change introduced in 0.7.1

### ISSUE THREAD

**Issue by BurntSushi** [rust-lang-nursery/bitflags#59]
See: https://github.com/Gekkio/imgui-rs/issues/42#issuecomment-279703432

In particular, it looks like https://github.com/rust-lang-nursery/bitflags/commit/67e4485d20ac79128843fb14abd3e8df742fcfae introduced a new `set` method that can break consumers if they had defined their own `set` method.

Perhaps we can yank `0.7.1` and release `0.8`?

**Comment by alexcrichton** [comment]
Sorry for the breakage!

**Comment by nox** [comment]
Could we yank 0.8 and think again about how to do `u128` support correctly? 0.8 includes a major regression where types that are locally imported cannot be used anymore as the flags type. This has already been broken in the past, and it would be nice if it didn't come back. Cf. https://github.com/rust-lang-nursery/bitflags/pull/51.

**Comment by nox** [comment]
Never mind, I didn't notice that the commit that broke that was reverted in the very same PR that introduced it.
