### ISSUE TITLE
Hide @_impl implementation detail from the bitflags! rustdoc

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/bitflags#63]
The rustdoc currently shows this distracting internal rule:

```rust
(@_impl flags $BitFlags:ident: $T:ty {
    $($(#[$Flag_attr:meta])* const $Flag:ident = $value:expr),+
}) => { ... };
```

**Comment by brson** [comment]
The way to do this is to create a new internal macro just for this case, probably with `__` prefix, and mark it `#[doc(hidden)]`.
