### ISSUE TITLE
pub(restricted) bitflags

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/bitflags#72]
cc https://github.com/rust-lang/rust/issues/32409 - maybe no action is warranted until this feature is stable.

```rust
bitflags! {
    pub(super) flags Flags: u8 {
        const A = 1
    }
}
```

**Comment by kennytm** [comment]
pub(restricted) is now stable. But I think it is still blocked by `:vis` matcher (rust-lang/rust#41022) to allow a proper fix.

**Comment by KodrAus** [comment]
It looks like using `:vis` here is unblocked now, right?
