### ISSUE TITLE
Add CI badges to Cargo.toml

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/bitflags#76]

**Comment by brson** [comment]
Looks like maybe bitflags isn't being tested on all platforms. There's no practical need, but istm it's desirable to have those badges for all tier 1 platforms. Should we set up the CI?

I imagine eventually having like a big wall of test results validating that all our crates do in fact work for all platforms. Maybe it just doesn't matter though.

**Comment by wy193777** [comment]
I created a pull request that add OS X test. #92

**Comment by brson** [comment]
Thanks @wy193777!

**Comment by brson** [comment]
Cargo.toml still needs CI badges.
