### ISSUE TITLE
Add keywords and categories to Cargo.toml

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/bitflags#77]

**Comment by rap2hpoutre** [comment]
I just added some keywords (one of my first contribution to "Call for participation"): https://github.com/rust-lang-nursery/bitflags/pull/93

I did not found any relevant categories here: https://crates.io/categories

**Comment by Cldfire** [comment]
This crate is actually a good fit for the [No Standard Library](https://crates.io/categories/no-std) category :)

**Comment by brson** [comment]
Thanks @rap2hpoutre !
