### ISSUE TITLE
Add an example of what the macro-expanded API looks like

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/bitflags#81]
This crate has a documentation problem in that it generates a bunch of methods, and they are hard to document. I believe the way we want to address this is by creating another module, containing a hand-coded API that looks like the bitflags produced API, and treat that entire module as documentation, sort of like error-chain does.

Will take some experimentation.

**Comment by Cldfire** [comment]
I will work on this later today if it has not been completed by then.

**Comment by koivunej** [comment]
Noticed that this was free and opened #99.
